# Site Settings
baseurl: ""
url : "https://repoleved33.github.io"

# Blog Settings
theme_settings :
  title : repoleved33 기술블로그
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpeg
    username : repoleved33
    description :  
    experience :
      - start : 2018-07-01
        end : 
        experience : web programmer

    skills : 
      - skill : Spring, java, javascript
        value : 50  # Percent value
        
  # Icons
  icons :
    email: repoleved33@gmail.com
    linkedin:  # Full URL 
    github: repoleved33
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : 
    comments : 'True'

# Pagination
paginate: 4
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
